name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A quick summary of the issue
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Include steps to reproduce the issue
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: specs
    attributes:
      label: Specs
      description: Include specifications that are directly related to the issue
      placeholder: |
        - Model:
        - GPU:
        - OS:
    validations:
      required: false
